# Generated by Django 4.2.1 on 2023-05-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scrapeddata",
            name="rating",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
