# Generated by Django 4.2.1 on 2023-05-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper_app", "0002_alter_scrapeddata_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scrapeddata",
            name="date_scraped",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
