# Generated by Django 4.2.1 on 2023-05-09 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scraper_app", "0003_alter_scrapeddata_date_scraped"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="scrapeddata", unique_together=set(),),
    ]
