# Generated by Django 4.2.1 on 2023-05-09 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper_app", "0005_alter_scrapeddata_date_scraped"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scrapeddata",
            name="price",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
